name: 'Build'
on: [pull_request, push]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Configure
        run: sh config.sh
      - name: Work
        run: cd build && ./graph
